export const mockTasks = [
  { id: 1, text: "Học React cơ bản", completed: false },
  { id: 2, text: "Viết component TodoList", completed: true },
  { id: 3, text: "Tìm hiểu Context API", completed: false },
  { id: 4, text: "Xây dựng chức năng filter", completed: false },
  { id: 5, text: "Thêm phân trang cho danh sách", completed: true },
  { id: 6, text: "Tối ưu hiệu suất render", completed: false },
  { id: 7, text: "Viết unit test cho component", completed: false },
  { id: 8, text: "Debug lỗi hiển thị", completed: true },
  { id: 9, text: "Thêm giao diện dark mode", completed: false },
  { id: 10, text: "Tối ưu code backend API", completed: false },
  { id: 11, text: "Tìm hiểu Redux cơ bản", completed: false },
  { id: 12, text: "Thiết kế UI với Figma", completed: true },
  { id: 13, text: "Triển khai lên production", completed: false },
  { id: 14, text: "Viết tài liệu dự án", completed: false },
  { id: 15, text: "Tổ chức code review", completed: true },
];
